version: '3.8'
services:
  redis:
    image: redis
    ports:
      - "6378:6379"
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 256M

  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 512M

  api:
#    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: cookiecutter_fastapi_v2
    ports:
      - "8080:8080"
    env_file:
      - docker-compose.env
    environment:
      - DEBUG=true
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - redis

  worker:
#    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    image: cookiecutter_fastapi_v2
    command: python cookiecutter_fastAPI_v2/worker.py
    env_file:
      - docker-compose.env
    environment:
      - DEBUG=true
    volumes:
      - ./:/app
    depends_on:
      - redis
      - postgres